### ISSUE TITLE
Вариативный товар

### ISSUE THREAD

**Issue by wireinet** [northmule/buy-one-click-woocommerce#4]
Добрый день! Все отлично работает, но с простыми товарами, вероятно...потому что у меня вариативный и ни один вариант не пишется в корзину! Можно это исправить как-то?

**Comment by northmule** [comment]
Добрый день! Вариативные в этом плагине не предусмотрены, есть расширение от известных мне людей для вариаций для этого плагина

**Comment by wireinet** [comment]
Добрый день, northmule!! Отлично! А есть где посмотреть?

**Comment by northmule** [comment]
Полное название дополнение кажется такое coderun-buy-one-click-woocommerce-variations

**Comment by wireinet** [comment]
Спасибо за помощь!
